[dependencies]

[package]
  cjc-version = "0.58.3"
  compile-option = ""
  description = "nothing here"
  link-option = "-lzstd"
  name = "zstd"
  output-type = "staticlib"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
